from . import van_trip
from . import van_trip_line
from . import van_sale_order
from . import van_sale_order_line
from . import pos_config
from . import pos_order
from . import van_payment
from . import van_nasiya
from . import res_partner
from . import res_users
from . import van_agent_summary
from . import van_customer
from . import van_pos_order
from . import van_dashboard_detail
from . import ir_http
from . import van_request
from . import van_taminotchi
from . import van_taminotchi_ledger_wizard
from . import product_product
from . import van_product
from . import telegram_utils
from . import res_config_settings
from . import van_ostatka_qarzi
from . import van_ledger_report_wizard
from . import van_agent_ostatka
from . import van_salary_payout
from . import van_sold_product_report_wizard
