{
    'name': 'Van Sales — Dori Savdosi Tizimi',
    'version': '1.1',
    'category': 'Sales/Point of Sale',
    'summary': 'Agentlar mashinasi savdosi, nasiya boshqaruvi va moliyaviy dashboard',
    'author': 'Logistika',
    'depends': [
        'base',
        'mail',
        'point_of_sale',
        'stock',
        'product',
    ],
    'data': [
        'security/van_sales_security.xml',
        'security/ir.model.access.csv',
        'data/van_sales_data.xml',
        'data/van_sales_bootstrap.xml',
        'views/van_sales_menu_root.xml',
        'views/pos_config_views.xml',
        'views/van_product_views.xml',
        'views/van_trip_views.xml',
        'views/van_sale_order_views.xml',
        'views/agent_views.xml',
        'views/van_customer_views.xml',
        'views/van_nasiya_views.xml',
        'views/van_payment_views.xml',
        'views/van_request_views.xml',
        'views/van_taminotchi_views.xml',
        'views/van_salary_views.xml',
        'views/van_sold_product_report_wizard_views.xml',
        'views/menu_views.xml',
        'views/van_ledger_report_wizard_views.xml',
        'views/van_dashboard_views.xml',
        'views/van_dashboard_detail_views.xml',
        'views/van_pos_order_views.xml',
        'views/van_mobile_pos_action.xml',
        'views/van_mobile_pos_templates.xml',
        'views/client_request_template.xml',
        'views/web_layout_inherit.xml',
        'views/login_layout_inherit.xml',
        'views/client_request_template.xml',
        'report/van_load_act_report.xml',
        'report/van_trip_report.xml',
        'views/res_config_settings_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'van_sales_pharma/static/src/css/van_sales.css',
            'van_sales_pharma/static/src/css/van_mobile_pos.css',
            'van_sales_pharma/static/src/js/van_agent_locker.js',
            'van_sales_pharma/static/src/js/van_dashboard.js',
            'van_sales_pharma/static/src/xml/van_dashboard.xml',
            'van_sales_pharma/static/src/js/van_mobile_pos.js',
            'van_sales_pharma/static/src/xml/van_mobile_pos.xml',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
    'post_init_hook': 'post_init_hook',
}
